### ISSUE TITLE
pcap filter for udp captures all outgoing packets

### ISSUE THREAD

**Issue by dadrian** [zmap/zmap#245]
filter is "udp || icmp", which means every packet we make will get captured by the pcap

**Comment by dadrian** [comment]
@amirian28 and @hmoore-r7, this is now fixed, correct?

**Comment by hmoore-r7** [comment]
Partially. Still getting some unrelated responses even with the current code, I think it narrowed it down to the other port check not working as expected (ran scans with a specific source port and still got replies not destined to our source port). It works OK for now, but due to our odd use case, we have to post-process results now. Fixing the second port check would go a long way to reducing the need to post-process here.

**Comment by hmoore-r7** [comment]
Woops, we definitely fixed the "outgoing treated as incoming" issue (this ticket). There are some additional issues that are causing unrelated replies to get recorded still.

**Comment by dadrian** [comment]
@hmoore-r7 so the problem is now there are valid responses that come in, but are destined to a different port than we were using for outgoing traffic?

**Comment by hmoore-r7** [comment]
Some of the probes we run result in buggy devices spamming the server indefinitely, as a result we get a constant stream of unrelated (to the current scan) UDP traffic. There appears to bug in the dst port checking function (not the src, which we moved already), that is including these unrelated replies, even when using a fixed source port. In other words, send as probe from A to B, we get back a response from C to A on a totally definitely port, and the existing filter seems to have a bug that accepts this.
