### ISSUE TITLE
 constraint_lookup_index: Assertion `index < con->root->count' failed.

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zmap#310]
This happened on c99e07777ec0c804609a4e44bea507a86ab598d3 (one commit behind the head of master as of this filing).

I can't recreate it. I've never seen it before or after.

```
$ sudo ./zmap -i eth1 --probe-module=dns --output-fields=* --target-port=53 --output-module=json --probe-args=MX,eecs.berkeley.edu 169.229.60.153 
Nov 17 20:58:08.830 [WARN] zmap: too few targets relative to senders, dropping to one sender
Nov 17 20:58:08.831 [INFO] zmap: output module: json
 0:00 0%; sent: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); app success: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00% app hitrate: 0.00%
zmap: lib/constraint.c:231: constraint_lookup_index: Assertion `index < con->root->count' failed.
```
(Minor editing to remove machine name and path.)

**Comment by jakeczyz** [comment]
I sporadically see this error too... on zmap 1.2.1 (the one in yum repos for CentOS 7.x).

**Comment by zakird** [comment]
@dadrian Do you have any ideas what's going on here? Is there a fix, or this a bug we can't really do anything with?

**Comment by dadrian** [comment]
I believe we fixed this.

**Comment by hasB4K** [comment]
Hello,

I have still this issue on zmap 2.1.1. It happens sporadically.
The command used:

$ zmap -p 42 {IP}/32 -f saddr -o scan_port_42 -b blacklist_zmap.tmp
```
Sep 09 11:23:18.419 [WARN] zmap: too few targets relative to senders, dropping to one sender
Sep 09 11:23:18.653 [INFO] zmap: output module: csv
zmap: /build/zmap-qmPEEi/zmap-2.1.1/lib/constraint.c:231: constraint_lookup_index: Assertion `index < con->root->count' failed.
Aborted (core dumped)
```

With the same IP, sometimes it does work, sometimes it doesn't... I don't understand why...

Some others (maybe useful) info:
I runned this on a machine with `Ubuntu 16.04.1 LTS` (x86_64 GNU/Linux) with the kernel version: `4.4.0-34-generic`

Regards,

**Comment by slayerulan** [comment]
Hello,
I still have this issue on zmap 2.1.1 too.

zmap: /build/zmap-qmPEEi/zmap-2.1.1/lib/constraint.c:231: constraint_lookup_index: Assertion `index < con->root->count' failed.
Aborted (core dumped)

OS: Ubuntu 16.04.1 LTS

**Comment by gescheit** [comment]
I have the same.

**Comment by davideandres95** [comment]
I have also observed it :(
